server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 10000000
  max_block_duration: 5m

metrics_generator:
  registry:
    external_labels:
      source: tempo

storage:
  trace:
    backend: local
    local:
      path: /tmp/traces
